### ISSUE TITLE
Question: syntax

### ISSUE THREAD

**Issue by alexsasharegan** [NoHomey/bind-decorator#7]
Thanks for the useful decorator! I was hoping you could explain the syntax at the line below, specifically the usage of the negation operator. It looks like it's being used as an existential operator, but that follows a different syntax. Just trying to demystify this so I can understand more about writing my own decorators.

https://github.com/NoHomey/bind-decorator/blob/master/src/index.ts#L14

**Comment by NoHomey** [comment]
It's to ensure type validity since [`TypedPropertyDescriptor<T>.value is optional value of type T`](https://github.com/Microsoft/TypeScript/blob/a6555921f4b1d51281b1241c69e91e5b82d2f07e/lib/lib.es5.d.ts#L1263).

**Comment by alexsasharegan** [comment]
Ah! Finally found it! Thanks for helping me learn a new TS trick!

<img width="891" alt="image" src="https://user-images.githubusercontent.com/16269252/33248186-dc0eb8c4-d2e0-11e7-970a-2c7dd06e6faa.png">
