### ISSUE TITLE
Unnecessary constants

### ISSUE THREAD

**Issue by bisubus** [NoHomey/bind-decorator#8]
As I see, [this commit](https://github.com/NoHomey/bind-decorator/commit/4b188a4d075e84d7ed1cb052c30f05368da8f73a) didn't provide reasoning for adding constants.

Unless constants are exported for testing reasons (and they are not), this can be considered antipattern. There won't be any performance gain from primitive constants either.

I would suggest to remove them, this will decrease package (which is tiny already) size by almost a half.

And thanks for this utility package that just works.

**Comment by MauricioAndrades** [comment]
i imagine this is to reuse the configuration and not needlessly create constants every time decorator is applied. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty `withValue` example on MDN.

**Comment by bisubus** [comment]
@MauricioAndrades These constants are primitives, there's no performance benefit in containing them in constants vs creating them each time in modern JS engines. Notice that the logic behind the descriptor didn't change.
